/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yrEZP0VHy3N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem } from "@/components/ui/dropdown-menu"
import { Card, CardContent } from "@/components/ui/card"

export function Component() {
  const [isOpen, setIsOpen] = useState(false)
  const [selectedFilters, setSelectedFilters] = useState({
    category: [],
    league: [],
  })
  const handleFilterChange = (type, value) => {
    if (type === "category") {
      setSelectedFilters({
        ...selectedFilters,
        category: selectedFilters.category.includes(value)
          ? selectedFilters.category.filter((item) => item !== value)
          : [...selectedFilters.category, value],
      })
    } else if (type === "league") {
      setSelectedFilters({
        ...selectedFilters,
        league: selectedFilters.league.includes(value)
          ? selectedFilters.league.filter((item) => item !== value)
          : [...selectedFilters.league, value],
      })
    }
  }
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 md:px-10 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2 font-bold text-lg" prefetch={false}>
          <ClubIcon className="w-6 h-6" />
          Football Shirts
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="flex items-center gap-2 hover:text-accent" prefetch={false}>
            <ShoppingCartIcon className="w-5 h-5" />
            Cart
          </Link>
          <Link href="#" className="flex items-center gap-2 hover:text-accent" prefetch={false}>
            <UserIcon className="w-5 h-5" />
            Profile
          </Link>
          <div className="group relative">
            <Button
              variant="ghost"
              className="flex items-center gap-2 hover:text-accent"
              onClick={() => setIsOpen(!isOpen)}
            >
              Categories
              <ChevronDownIcon className="w-5 h-5 transition-transform group-data-[state=open]:rotate-180" />
            </Button>
            {isOpen && (
              <div className="absolute z-10 bg-primary shadow-lg rounded-md p-2 grid gap-2">
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  Current
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  Retro
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  National Teams
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  England Premier League
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  Spain La Liga
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  Germany Bundesliga
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  Italy Serie A
                </Link>
                <Link
                  href="#"
                  className="px-4 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  France Ligue 1
                </Link>
              </div>
            )}
          </div>
        </nav>
        <div className="md:hidden">
          <Button variant="ghost" size="icon">
            <MenuIcon className="w-6 h-6" />
            <span className="sr-only">Toggle menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1 flex">
        <aside className="bg-muted p-6 md:p-10 w-64 hidden md:block">
          <h2 className="text-2xl font-bold mb-6">Filters</h2>
          <div className="grid gap-6">
            <div>
              <h3 className="text-lg font-semibold mb-2">Category</h3>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.category.includes("current")}
                    onCheckedChange={() => handleFilterChange("category", "current")}
                  />
                  Current
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.category.includes("retro")}
                    onCheckedChange={() => handleFilterChange("category", "retro")}
                  />
                  Retro
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.category.includes("national-teams")}
                    onCheckedChange={() => handleFilterChange("category", "national-teams")}
                  />
                  National Teams
                </Label>
              </div>
            </div>
            <div>
              <h3 className="text-lg font-semibold mb-2">League</h3>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.league.includes("england-premier-league")}
                    onCheckedChange={() => handleFilterChange("league", "england-premier-league")}
                  />
                  England Premier League
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.league.includes("spain-laliga")}
                    onCheckedChange={() => handleFilterChange("league", "spain-laliga")}
                  />
                  Spain La Liga
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.league.includes("germany-bundesliga")}
                    onCheckedChange={() => handleFilterChange("league", "germany-bundesliga")}
                  />
                  Germany Bundesliga
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.league.includes("italy-serie-a")}
                    onCheckedChange={() => handleFilterChange("league", "italy-serie-a")}
                  />
                  Italy Serie A
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox
                    checked={selectedFilters.league.includes("france-ligue-1")}
                    onCheckedChange={() => handleFilterChange("league", "france-ligue-1")}
                  />
                  France Ligue 1
                </Label>
              </div>
            </div>
          </div>
        </aside>
        <div className="flex-1">
          <section className="bg-muted py-8 px-6 md:px-10">
            <div className="max-w-3xl mx-auto">
              <h1 className="text-3xl font-bold mb-4">Find Your Perfect Football Shirt</h1>
              <div className="relative">
                <SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <div className="flex items-center gap-2">
                  <Input
                    type="search"
                    placeholder="Search by team, style, or price"
                    className="w-full px-12 py-3 rounded-md"
                  />
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="outline" className="h-[42px] gap-1">
                        <FilterIcon className="w-5 h-5" />
                        <span>Filters</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent className="w-[200px]">
                      <DropdownMenuLabel>Filter by</DropdownMenuLabel>
                      <DropdownMenuSeparator />
                      <DropdownMenuCheckboxItem>Current</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>Retro</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>National Teams</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>England Premier League</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>Spain La Liga</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>Germany Bundesliga</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>Italy Serie A</DropdownMenuCheckboxItem>
                      <DropdownMenuCheckboxItem>France Ligue 1</DropdownMenuCheckboxItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>
            </div>
          </section>
          <section className="py-12 px-6 md:px-10">
            <div className="max-w-6xl mx-auto">
              <h2 className="text-2xl font-bold mb-6">Featured Shirts</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
                <Card>
                  <img
                    src="/retro-holanda.jpg"
                    alt="Shirt 1"
                    width={300}
                    height={400}
                    className="rounded-t-md object-cover w-full h-64"
                    style={{ aspectRatio: "300/400", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold mb-2">Manchester United Home Shirt</h3>
                    <p className="text-muted-foreground mb-4">$79.99</p>
                    <Button>Add to Cart</Button>
                  </CardContent>
                </Card>
                <Card>
                  <img
                    src="/retro-real-madrid.png"
                    alt="Shirt 2"
                    width={300}
                    height={400}
                    className="rounded-t-md object-cover w-full h-64"
                    style={{ aspectRatio: "300/400", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold mb-2">Brazil National Team Away Shirt</h3>
                    <p className="text-muted-foreground mb-4">$69.99</p>
                    <Button>Add to Cart</Button>
                  </CardContent>
                </Card>
                <Card>
                  <img
                    src="/retro-holanda.jpg"
                    alt="Shirt 3"
                    width={300}
                    height={400}
                    className="rounded-t-md object-cover w-full h-64"
                    style={{ aspectRatio: "300/400", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold mb-2">Juventus Retro Home Shirt</h3>
                    <p className="text-muted-foreground mb-4">$59.99</p>
                    <Button>Add to Cart</Button>
                  </CardContent>
                </Card>
                <Card>
                  <img
                    src="/retro-real-madrid.png"
                    alt="Shirt 4"
                    width={300}
                    height={400}
                    className="rounded-t-md object-cover w-full h-64"
                    style={{ aspectRatio: "300/400", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-xl font-bold mb-2">England National Team Home Shirt</h3>
                    <p className="text-muted-foreground mb-4">$74.99</p>
                    <Button>Add to Cart</Button>
                  </CardContent>
                </Card>
              </div>
            </div>
          </section>
          <section className="bg-muted py-12 px-6 md:px-10">
            <div className="max-w-6xl mx-auto">
              <h2 className="text-2xl font-bold mb-6">Shop by Category</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
                <Link href="#" className="group" prefetch={false}>
                  <div className="relative rounded-md overflow-hidden">
                    <img
                      src="/placeholder.svg"
                      alt="Current Shirts"
                      width={400}
                      height={300}
                      className="w-full h-64 object-cover group-hover:opacity-80 transition-opacity"
                      style={{ aspectRatio: "400/300", objectFit: "cover" }}
                    />
                    <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                      <h3 className="text-2xl font-bold text-white">Current Shirts</h3>
                    </div>
                  </div>
                </Link>
                <Link href="#" className="group" prefetch={false}>
                  <div className="relative rounded-md overflow-hidden">
                    <img
                      src="/placeholder.svg"
                      alt="Retro Shirts"
                      width={400}
                      height={300}
                      className="w-full h-64 object-cover group-hover:opacity-80 transition-opacity"
                      style={{ aspectRatio: "400/300", objectFit: "cover" }}
                    />
                    <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                      <h3 className="text-2xl font-bold text-white">Retro Shirts</h3>
                    </div>
                  </div>
                </Link>
                <Link href="#" className="group" prefetch={false}>
                  <div className="relative rounded-md overflow-hidden">
                    <img
                      src="/placeholder.svg"
                      alt="National Team Shirts"
                      width={400}
                      height={300}
                      className="w-full h-64 object-cover group-hover:opacity-80 transition-opacity"
                      style={{ aspectRatio: "400/300", objectFit: "cover" }}
                    />
                    <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                      <h3 className="text-2xl font-bold text-white">National Team Shirts</h3>
                    </div>
                  </div>
                </Link>
                <Link href="#" className="group" prefetch={false}>
                  <div className="relative rounded-md overflow-hidden">
                    <img
                      src="/placeholder.svg"
                      alt="England Premier League Shirts"
                      width={400}
                      height={300}
                      className="w-full h-64 object-cover group-hover:opacity-80 transition-opacity"
                      style={{ aspectRatio: "400/300", objectFit: "cover" }}
                    />
                    <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                      <h3 className="text-2xl font-bold text-white">England Premier League</h3>
                    </div>
                  </div>
                </Link>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function ClubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.28 9.05a5.5 5.5 0 1 0-10.56 0A5.5 5.5 0 1 0 12 17.66a5.5 5.5 0 1 0 5.28-8.6Z" />
      <path d="M12 17.66L12 22" />
    </svg>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
